import { INDEXFORMAT_UINT8, INDEXFORMAT_UINT16, INDEXFORMAT_UINT32 } from "../constants";

export enum IndexFormat {
  UINT8 = INDEXFORMAT_UINT8,
  UINT16 = INDEXFORMAT_UINT16,
  UINT32 = INDEXFORMAT_UINT32,
}
