const VERSION = "0.0.1";

const GEOMETRY_TYPE = {
  "POINTS": "POINTS",
  "TRIANGLES": "TRIANGLES",
  "TRIANGLE_FAN": "TRIANGLE_FAN",
  "LINE_LOOP": "LINE_LOOP",
}

const SIDE = {
  FrontSide: 0,
  BackSide: 1,
  DoubleSide: 2
}

const BLENDING_TYPE = {
  // rgba 整体混合
  "RGBA": "RGBA",
  // rgb,a分开混合
  "RGB_A": "RGB_A"
}

const BLENDING_FACTOR = {
  "ZERO": "ZERO",
  "ONE": "ONE",
  "SRC_COLOR": "SRC_COLOR",
  "ONE_MINUS_SRC_COLOR": "ONE_MINUS_SRC_COLOR",
  "SRC_ALPHA": "SRC_ALPHA",
  "ONE_MINUS_SRC_ALPHA": "ONE_MINUS_SRC_ALPHA",

  "DST_COLOR": "DST_COLOR",
  "ONE_MINUS_DST_COLOR": "ONE_MINUS_DST_COLOR",
  "DST_ALPHA": "DST_ALPHA",
  "ONE_MINUS_DST_ALPHA": "ONE_MINUS_DST_ALPHA",
}
export {
  SIDE,
  VERSION,
  GEOMETRY_TYPE,
  BLENDING_TYPE,
  BLENDING_FACTOR
}
